run_tests.sh: run each test in a separate directory and paste all generated files into one.
Updated tests: changes are insignificant (the order in which multiple
generated files are concatenated has changed).

diff --git a/re2c/run_tests.sh.in b/re2c/run_tests.sh.in
--- a/re2c/run_tests.sh.in
+++ b/re2c/run_tests.sh.in
@@ -102,85 +102,79 @@ run_pack() {
 	local errcnt=0
 	for x in $*
 	do
+		cd $test_blddir
+
 		# preserve directory structure unless given explicit args
 		if [ -z "$test_srcdir" ]
 		then
-			local outx=$test_blddir/`basename $x`
+			local outx=`basename $x`
 		else
-			local outx=${test_blddir}${x:${#test_srcdir}}
+			# remove prefix
+			local outx=${x:$((${#test_srcdir} + 1))}
 			mkdir -p `dirname $outx`
 		fi
-		local outname=${outx%.re}.c.temp
-		local outdiff=${outx%.re}.c.diff
 		local outc="${outx%.re}.c"
 
-		local switches=`basename $x | sed -e 's/^[^.]*\.\(.*\)\.re$/-\1/g' -e 's/^[^-].*//g' -e 's/\([^ ]\)--/\1 --/g' -e 's/(\([^)]*\))/ \1/g' -e 's/- //g'`
-		local outh=` printf "%s" "$switches" | grep -e '^-[^t -]*t[^ -]\+' | sed -e 's,^-[^t -]*t\([^ -]\+\),'"$test_blddir"'/\1,g'`
-		local switches=`printf "%s" "$switches" | sed -e 's,^-\([^ot-]*[ot]\)\(.*\)$,-\1'"$test_blddir"'/\2,g'`
+		local switches=`basename "$x" | sed -e 's/^[^.]*\.\(.*\)\.re$/-\1/g' -e 's/^[^-].*//g' -e 's/\([^ ]\)--/\1 --/g' -e 's/(\([^)]*\))/ \1/g' -e 's/- //g'`
 		local switches="$switches -o $outc"
 		# enable warnings globally
 		local switches="$switches -W"
 
-		local cmd="${valgrind} ${wine} ${re2c} $switches $x"
-
 		if [ $skeleton -eq 1 ]
 		then
-			cmd="${cmd} --skeleton -Werror-undefined-control-flow"
-			mkdir -p `dirname "$outc"`
+			local switches="$switches --skeleton -Werror-undefined-control-flow"
 
 			local status=""
-			[ -z $status ] && status=`$cmd 2>"$outc".stderr || echo "FAIL_RE2C"`
-			[ -z $status ] && status=`gcc -Wall -Wextra -o "$outc".out "$outc" 2>>"$outc".stderr || echo "FAIL_CC"`
-			[ -z $status ] && status=`./"$outc".out 2>>"$outc".stderr || echo "FAIL_RUN"`
+			[ -z $status ] && status=`${valgrind} ${wine} ../${re2c} $switches "../$x" 2>"$outc.stderr" || echo "FAIL_RE2C"`
+			[ -z $status ] && status=`gcc -Wall -Wextra -o "$outc.out" "$outc" 2>>"$outc.stderr" || echo "FAIL_CC"`
+			[ -z $status ] && status=`./"$outc.out" 2>>"$outc.stderr" || echo "FAIL_RUN"`
 			[ -z $status ] && status="OK"
 			if [ $status = "OK" -o $status = "FAIL_RE2C" ]
 			then
 				[ $keep_tmp_files -eq 0 ] && rm -f "$outc"{,.line*.{input,keys},.stderr,.out}
 			else
-				cp -f $x $outx
+				cp -f "../$x" "$outx"
 				local errcnt=$(($errcnt + 1))
 			fi
 
-			echo "$status $x"
+			printf "%-10s $outx\n" "$status"
 		else
-			local outname_stderr="${outname}.stderr"
-			$cmd 2>$outname_stderr
-			cat $outname_stderr $outc > $outname
-			rm $outname_stderr $outc
-			# don't forget '-S, --skeleton' files
-			for f in `find $(dirname $outc) -type f -name "$(basename $outc).line*.input"`
-			do
-				cat $f ${f%.input}.keys >> $outname
-				rm $f ${f%.input}.keys
-			done
-			# don't forget '-t, --type-header' files
-			[ -n "$outh" ] && cat "$outh" >> $outname && rm "$outh"
+			# create sandbox
+			tmpdir="tmp_$log" \
+				&& mkdir "$tmpdir" \
+				&& cd "$tmpdir" \
+				&& mkdir -p `dirname "$outx"` \
+				&& cp "../../$x" "$outx"
+			# run re2c
+			$valgrind $wine ../../$re2c $switches "$outx" 2>"$outc.stderr" 1>&2
+			# paste all files dropped by re2c into output file
+			rm "$outx" && find . -type f \
+				| sort \
+				| xargs cat \
+				| LC_ALL=C sed -e 's,/\* Generated by re2c .*\*/,/\* Generated by re2c \*/,g' \
+				>> "../$outc"
+			# cleanup sandbox
+			cd .. \
+				&& rm -rf "$tmpdir"
 
-			LC_ALL=C sed -i $outname \
-				-e "s,$x,`basename $x`,g" \
-				-e "s,$test_blddir/,,g" \
-				-e 's,/\* Generated by re2c .*\*/,/\* Generated by re2c \*/,g'
-
-			if test ! -f ${x%.re}.c
+			# compare results
+			local c="${x%.re}.c"
+			local status=""
+			[ -z $status ] && status=`[ -f "../$c" ] || echo "MISSING"`
+			[ -z $status ] && status=`$diff_prog "../$c" "$outc" > "$outc.diff" || echo "FAIL"`
+			[ -z $status ] && status="OK"
+			if [ $status = "OK" ]
 			then
-				echo "FAIL missing ${x%.re}.c"
-				local errcnt=$(($errcnt + 1))
-				cp -f $x $outx
+				rm "$outc" "$outc.diff"
 			else
-				local r=`$diff_prog ${x%.re}.c $outname > $outdiff; echo $?`
-				if [[ $r == 0 ]]
-				then
-					echo "OK $x: $switches"
-					rm $outname
-				else
-					echo "FAIL $x: $switches"
-					local errcnt=$(($errcnt + 1))
-					cp -f $x $outx
-					cp -f ${x%.re}.c ${outx%.re}.c
-				fi
+				cp -f "../$x" "$outx"
+				cp -f "../$c" "$outc.orig"
+				local errcnt=$(($errcnt + 1))
 			fi
-			test -f $outdiff -a ! -s $outdiff && rm -f $outdiff
+
+			printf "%-10s $outx\n" "$status"
 		fi
+		cd ..
 	done
 	echo $errcnt > $log
 }
